
#ifndef GOFCONFIG_H
#define GOFCONFIG_H


#define MAP_HEIGHT 1024
#define MAP_WIDTH  1024

#define INTERACT_BLOCKS_AROUND 5 

#define MIN_LIFES_FOR_SURVIVE 34
#define MAX_LIFES_FOR_SURVIVE 58

#define MIN_LIFES_FOR_BIRTH 34
#define MAX_LIFES_FOR_BIRTH 45

#endif // GOFCONFIG_H
